name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run tests
        run: bash tests/run-tests.sh --verbose

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run tests
        shell: pwsh
        run: .\tests\run-tests.ps1 -Verbose
